data_cols = [
       'bus_date', 'pos_venue_id', 'order_id', 'sales_hr', 'time_zone', 
       'order_local_time', 'device_order_id', 'ord_beg_time', 'item_count', 
       'ord_close_time', 'gross_total', 'net_total', 'taxes', 'reduction_amt', 
       'cust_prof_id', 'mobile_ord_fl', 'original_order_id', 'vendor_loc_id', 
       'fee_amt', 'tip_amount', 'sync_status', 'vendor_id', 'menu_vendor_id', 
       'refund_vendor_id', 'refund_venue_id', 'pos_terminal_id', 'reduction_cd', 
       'order_tab_id', 'order_status_cd', 'united_account_id', 'voucher_number',  
       'card_type', 'payment_type', 'account_id', 'cash_recycler_tiny_code', 
       'transaction_seq_nu', 'payment_amount', 'payment_amt_rewards_points',  
       'emp_email', 'cust_first_name', 'cust_last_name', 'activity_status_code', 
       'employee_role_name', 'employer_id', 'employer_name', 'default_email_address',
    #  'cust_emply_verified_fl', 'cust_emply_active_fl', 'primary_email_address', 
    #  'employer_active_fl', 'birth_date', 'exclusive_tax', 'default_phone_number', 
    #  'transaction_id', 'inclusive_tax',  'company_id', 'src_sys_id',
    #  'primary_email_opt_in_fl', 'primary_email_active_fl',
    #  'primary_email_verified_fl', 'extra_ph_number', 'active_fl', 
       'is_fraud'
       ]
date_cols = [
    "bus_date",
    "order_local_time",
    "ord_beg_time",
    "ord_close_time",
]

reduction_cds = {
    "AIRPORT_DISCOUNT": "INT_AIRPORT_DISCOUNT",
    "Airport": "INT_AIRPORT_DISCOUNT",
    "AMERICAN_DISCOUNT": "INT_AMERICAN_DISCOUNT",
    "Chase": "INT_UNITED_CHASE",
    "CREW_DISCOUNT": "INT_CREW_DISCOUNT",
    "Crew": "INT_CREW_DISCOUNT",
    "DELTA_DISCOUNT": "INT_DELTA_DISCOUNT",
    "Delta": "INT_DELTA_DISCOUNT",
    "JETBLUE_DISCOUNT": "INT_JETBLUE_DISCOUNT",
    "MANAGER_DISCOUNT": "INT_MANAGER_DISCOUNT",
    "Manager Meal": "INT_MANAGER_DISCOUNT",
    "SOUTHWEST_DISCOUNT": "INT_SOUTHWEST_DISCOUNT",
    "SPIRIT_DISCOUNT": "INT_SPIRIT_DISCOUNT",
    "UNITED_CHASE": "INT_UNITED_CHASE",
    "UNITED_DISCOUNT": "INT_UNITED_DISCOUNT",
}
# card_types = {
#     "MC": "MASTERCARD",
#     "Mastercard": "MASTERCARD",
#     "AMEX": "AMERICAN EXPRESS",
#     "Amex": "AMERICAN EXPRESS",
#     "DISC": "DISCOVER",
#     "Discover": "DISCOVER",
#     "DISCOVER (DC)": "DISCOVER",
#     "Invoice": "INVOICE/ MILITARY",
#     "Military": "INVOICE/ MILITARY",
#     "Cash": "CASH",
#     "Visa": "VISA",
#     "Checkout": "CHECKOUT",
# }

# payment_types = {
#     "MILITARY_VOUCHER": "INVOICE/ MILITARY",
#     "INVOICE_VOUCHER": "INVOICE/ MILITARY",
# }

card_types = {
    "Visa": "VISA",
    "VS": "VISA",
    # "VISA CREDIT": "VISA",
    # "VISA DEBIT": "VISA",
    "MC": "MASTERCARD",
    "Mastercard": "MASTERCARD",
    "MasterCard": "MASTERCARD",
    "AMEX": "AMERICAN EXPRESS",
    "Amex": "AMERICAN EXPRESS",
    "AMERICAN": "AMERICAN EXPRESS",
    "AmEx": "AMERICAN EXPRESS",
    "DISC": "DISCOVER",
    "Discover": "DISCOVER",
    "DISCOVER (DC)": "DISCOVER",
    "Cash": "CASH",
    "Invoice": "VOUCHER",
    "Military": "VOUCHER",
    # "JCB": "Other",
    # "CUP": "Other",
    # "UP": "Other",
    # "Glory": "Other",
    # "PayPal": "Other",
    # "Checkout": "Other",
}

payment_types = {
    # "MANUAL_CASH": "CASH",
    # "UNITED_MILES": "REWARD",
    "INVOICE_VOUCHER": "VOUCHER",
    "GIFT_VOUCHER": "VOUCHER",
    "MILITARY_VOUCHER": "VOUCHER",
    }

dtype = {
    "fee_amt": "float64",
    "reduction_cd": "object",
    "sync_status": "object",
    "order_status_cd": "object",
    "order_modified_time": "object",
    "country_id": "object",
    "pos_venue_id": "object",
    "order_id": "object",
    "transaction_id": "object",
    "device_order_id": "object",
    "order_event_type_id": "object",
    "pos_order_type_id": "object",
    "day_part_id": "object",
    "reduction_id": "object",
    "promo_id": "object",
    "cust_prof_id": "object",
    "original_order_id": "object",
    "order_status_id": "object",
    "device_id": "object",
    "vendor_loc_id": "object",
    "mode_id": "object",
    "order_source_id": "object",
    "srce_sys_id": "object",
    "src_sys_id": "object",
    "vendor_id": "object",
    "menu_vendor_id": "object",
    "pos_order_uuid": "object",
    "refund_vendor_id": "object",
    "refund_venue_id": "object",
    "pos_terminal_id": "object",
    "order_tab_id": "object",
    "united_account_id": "object",
    'scheduled_local_dtm': 'object',
    "employee_role_name": "object",
    "employer_name": "object",
    "reduction_cd": "object",
    "default_phone_number": "object",
    "extra_ph_number": "object",
    "country_id": "object",
    "cust_prof_id": "object",
    "cust_prof_key": "object",
    "employee_role_id": "object",
    "employer_id": "object",
    "identity_provider_id": "object",
    "company_id": "object",
    "birth_date": "datetime64[ns]",
    "cash_recycler_tiny_code": "object",
    "emp_email": "object",
    "voucher_number": "object",
    "country_id": "object",
    "pos_venue_id": "object",
    "order_id": "object",
    "src_sys_id": "object",
    "transaction_id": "object",
    "vendor_id": "object",
    "account_id": "object",
}